[package]
name = "embedded-test"
version = "0.2.1"
edition = "2021"
repository = "https://github.com/probe-rs/embedded-test"
license = "MIT OR Apache-2.0"
keywords = ["embedded", "test", "testing",  "test-runner", "test-framework"]
description = "A test harness and runner for embedded devices"
categories = ["embedded", "no-std", "development-tools::testing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Dependencies when this crate is used as library
[dependencies]
semihosting = { version ="0.1.4", features = ["args"] }
embedded-test-macros = {version="0.2.0",path = "./macros" }
defmt = { version = "0.3.5", optional = true }
log = { version = "0.4.20", optional = true}
serde = { version = "1.0.193", default-features = false, features = ["derive"] }
serde-json-core = { version = "0.5.1"  }
heapless = "0.8.0"
embassy-executor = { version = "0.4.0", optional=true, default-features = false }

[features]
defmt = ["dep:defmt"]
log = ["dep:log"]

embassy = ["embedded-test-macros/embassy", "dep:embassy-executor"]